# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferrogw" do
  version "1.5.9"

  on_macos do
    on_intel do
      sha256 "cfdfffbf91e8bb7b3222872fc3363ed671081b9b592bf49c2e02cbf6b66f0dbf"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c76ae452445380e569a384714d5335ade0dc315e8d39ec112e0a2b2b700dcae2"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f29a3b572c1f350fba54f3c36516fccb8c86994577f69107f170af7fd03fc40"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e23b8670337c03b1fdb79c20d2942b7689b3d1a0db045eb97455a2b6fa054d97"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ferrogw"
  desc "Open-source AI Gateway for LLM routing"
  homepage "https://github.com/ferro-labs/ai-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferrogw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ferrogw"]
    end
  end

  # No zap stanza required

end
