# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferrogw" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "c752327b2b57b8fb1383c906d42d3540dbf4064c9910b9751f0dc6b27844df40"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "548d05fa85ab8fcee97ce1de3ff87e032d0a708c0a7883408c1358b487c973dc"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ea9cf8200ce759d103ffc11e13cbca61718f09d0643129a5283c377c52f7ca2"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc5325b6ddebbb009b4f90cee3f6b85bcd9f2921623483f6a4dde026936bb272"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ferrogw"
  desc "Open-source AI Gateway for LLM routing"
  homepage "https://github.com/ferro-labs/ai-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferrogw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ferrogw"]
    end
  end

  # No zap stanza required

end
