# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferrogw" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "1a156b9fadba9a3d7c0b83fb10b311d012431029aaceedc0e085cfe77dbc017b"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9ec93ec61531b4834aa8dbbd5a05e50c183c2e4d15ea474dc6609ec8792e44d"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c3b1bbb026db495ae781054235480fe46e41196115fef75c92ca6d73b371de1"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d475d734c30879e206252e46a9e5722882de9865e77bdf30bda29ed7ddd780d7"
      url "https://github.com/ferro-labs/ai-gateway/releases/download/v#{version}/ferrogw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ferrogw"
  desc "Open-source AI Gateway for LLM routing"
  homepage "https://github.com/ferro-labs/ai-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferrogw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ferrogw"]
    end
  end

  # No zap stanza required

end
